<a href="https://colab.research.google.com/github/SamBroberg/Linear_Algebra_Projects/blob/main/Determinants.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"
print(ll)

loaded


In [ ]:
A = np.matrix([[3,2,3],
              [-6,1,-10],
              [-8,-9,-9]])
A


matrix([[  3,   2,   3],
        [ -6,   1, -10],
        [ -8,  -9,  -9]])

In [ ]:
B = np.matrix([[1,-2,1],
              [5,5,4],
              [4,0,0]])
B

matrix([[ 1, -2,  1],
        [ 5,  5,  4],
        [ 4,  0,  0]])

In [ ]:
C = np.matrix([[1,0,0],
              [0,2,0],
              [-3,-2,1]])
C

matrix([[ 1,  0,  0],
        [ 0,  2,  0],
        [-3, -2,  1]])

In [ ]:
print(np.linalg.det(A))
print(np.linalg.det(B))
print(np.linalg.det(C))

-58.999999999999964
-51.999999999999986
1.9999999999999998


In [ ]:
AB = A * B
BA = B * A
print(AB)
print()
print(BA)

[[ 25   4  11]
 [-41  17  -2]
 [-89 -29 -44]]

[[  7  -9  14]
 [-47 -21 -71]
 [ 12   8  12]]


In [ ]:
print('AB:',np.linalg.det(AB))
print('BA:',np.linalg.det(BA))

AB: 3067.9999999999973
BA: 3067.9999999999973


In [ ]:
def findeterminant(mat1,mat2,mat3):
  print('A:',np.linalg.det(mat1))
  print('B:',np.linalg.det(mat2))
  print('C:',np.linalg.det(mat3))
  AB = A * B
  BA = B * A
  AC = A * C
  CA = C * A
  CB = C * B
  BC = B * C 
  print('AB:',np.linalg.det(AB))
  print('BA:',np.linalg.det(BA))
  print('AC:',np.linalg.det(AC))
  print('CA:',np.linalg.det(CA))
  print('BC:',np.linalg.det(BC))
  print('CB:',np.linalg.det(CB))
  print()
  print('AB:',AB)
  print('BA:',BA)
  print('AC:',AC)
  print('CA:',CA)
  print('BC:',BC)
  print('CB:',CB)

In [ ]:
findeterminant(A,B,C)

A: -58.999999999999964
B: -51.999999999999986
C: 1.9999999999999998
AB: 3067.9999999999973
BA: 3067.9999999999973
AC: -118.00000000000004
CA: -118.00000000000004
BC: -103.99999999999999
CB: -104.00000000000007

AB: [[ 25   4  11]
 [-41  17  -2]
 [-89 -29 -44]]
BA: [[  7  -9  14]
 [-47 -21 -71]
 [ 12   8  12]]
AC: [[ -6  -2   3]
 [ 24  22 -10]
 [ 19   0  -9]]
CA: [[  3   2   3]
 [-12   2 -20]
 [ -5 -17   2]]
BC: [[-2 -6  1]
 [-7  2  4]
 [ 4  0  0]]
CB: [[  1  -2   1]
 [ 10  10   8]
 [ -9  -4 -11]]


In [ ]:
ABC = A*B*C
ACB = A*C*B
CBA = C*B*A

In [ ]:
print('ABC:',np.linalg.det(ABC))
print('ACB:',np.linalg.det(ACB))
print('CBA:',np.linalg.det(CBA))

ABC: 6135.999999999995
ACB: 6136.000000000006
CBA: 6136.000000000006


In [ ]:
A = np.matrix([[10,7],
                [8,9]])
A

matrix([[10,  7],
        [ 8,  9]])

In [ ]:
B = np.matrix([[-10,-1],
                [-4,7]])
B

matrix([[-10,  -1],
        [ -4,   7]])

In [ ]:
C = np.matrix([[1,-3],
                [7,7]])
C

matrix([[ 1, -3],
        [ 7,  7]])

In [ ]:
findeterminant(A,B,C)

A: 34.00000000000001
B: -74.00000000000003
C: 27.999999999999996
AB: -2515.999999999999
BA: -2516.0000000000014
AC: 951.9999999999997
CA: 951.9999999999997
BC: -2071.9999999999995
CB: -2071.9999999999995

AB: [[-128   39]
 [-116   55]]
BA: [[-108  -79]
 [  16   35]]
AC: [[59 19]
 [71 39]]
CA: [[-14 -20]
 [126 112]]
BC: [[-17  23]
 [ 45  61]]
CB: [[  2 -22]
 [-98  42]]


In [ ]:
ABC = A*B*C
ACB = A*C*B
CBA = C*B*A

In [ ]:
print('ABC:',np.linalg.det(ABC))
print('ACB:',np.linalg.det(ACB))
print('CBA:',np.linalg.det(CBA))


ABC: -70447.99999999994
ACB: -70447.99999999994
CBA: -70447.99999999994
