<a href="https://colab.research.google.com/github/SamBroberg/Linear_Algebra_Projects/blob/main/Practice_with_Gram_Schmidt_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import the numpy library....

import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [2]:
#  How do I do a dot product?
np.dot([ 1, 2], [ 3, 4])

# How do I find the magnitude in np?
np.sqrt(np.dot([1,2],[1,2]))

2.23606797749979

In [4]:
#  Define the original vectors:

r1 = [ 3, 0, 3, 0 ]
r2 = [ 3, 2, 3, 3]
r3 = [ (-7), (-4), (-5), (-6)]
r4 = [ (-7), (-3), (-11), 2]

# Look at r1:
r4


[-7, -3, -11, 2]

In [5]:
#  Find the first nice basis vector u1:

# 1:  Pick a new vector
r1

# 2:  Subtract the projection of r1 onto the nice basis  u1, u2, u3...
#     and save this as a temp vector n1
n1 = r1
n1

# 3:  Find the magnitude of n1
np.sqrt(np.dot(n1, n1))

# 4:  Create the nice basis vector u1 = 1/ | n1 |  * n1
u1 = n1 / np.sqrt(np.dot(n1,n1))
u1


array([0.70710678, 0.        , 0.70710678, 0.        ])

In [6]:
# Check that u1 has magnitude 1:
np.dot(u1, u1)

1.0000000000000002

In [7]:
#  Find the second nice basis vector u2:

# 1:  Pick a new vector
r2

# 2:  Subtract the projection of r2 onto the nice basis  u1, u2, u3...
#     and save this as a temp vector n2
n2 = r2 - np.dot(r2, u1) * u1
n2

# 3:  Find the magnitude of n2
np.sqrt(np.dot(n2, n2))

# 4:  Create the nice basis vector u2 = 1/ | n2 |  * n2
u2 = n2 / np.sqrt(np.dot(n2,n2))
u2

array([-1.23168186e-16,  5.54700196e-01, -1.23168186e-16,  8.32050294e-01])

In [8]:
#  Check that u1 and u2 are orthogonal:
np.dot(u1, u2)

# Check that u2 has magnitude 1:
np.dot(u2, u2)

1.0

In [9]:
# Find the third nice basis vector u3:

# 1:  Pick a new vector
r3

# 2:  Subtract the projection of r3 onto the nice basis  u1, u2, ...
#     and save this as a temp vector n3
n3 = r3 - np.dot(r3, u1) * u1 - np.dot(r3, u2) * u2
n3

# 3:  Find the magnitude of n2
np.sqrt(np.dot(n3, n3))

# 4:  Create the nice basis vector u3 = 1/ | n3 |  * n3
u3 = n3 / np.sqrt(np.dot(n3,n3))
u3

array([-7.07106781e-01, -3.14018492e-16,  7.07106781e-01, -6.28036983e-16])

In [10]:
#  Check that u3 is orthogonal to u1 and u2
print(np.dot(u1, u3))
print(np.dot(u2, u3))
print(np.dot(u3,u3))

-1.0146536357569526e-17
-6.967444759389139e-16
0.9999999999999998


In [11]:
# Find the third nice basis vector u4:

# 1:  Pick a new vector
r4

# 2:  Subtract the projection of r4 onto the nice basis  u1, u2, u3 ...
#     and save this as a temp vector n4
n4 = r4 - np.dot(r4, u1) * u1 - np.dot(r4, u2) * u2 - np.dot(r4, u3) * u3
n4

# 3:  Find the magnitude of n4
np.sqrt(np.dot(n4, n4))

# 4:  Create the nice basis vector u4 = 1/ | n4 |  * n4
u4 = n4 / np.sqrt(np.dot(n4,n4))
u4

array([-1.23168186e-16, -8.32050294e-01,  1.23168186e-16,  5.54700196e-01])

In [12]:
# Check that u4 is orthogonal to u1, u2, and u3
# and check that |u4| = 1
print(np.dot(u4, u1))
print(np.dot(u4, u2))
print(np.dot(u4, u3))
print(np.dot(u4, u4))


4.3370130851795835e-33
-1.203390859898517e-15
8.709305949236507e-17
1.0000000000000002


In [15]:
print(u1)
print(u2)
print(u3)
print(u4)

[0.70710678 0.         0.70710678 0.        ]
[-1.23168186e-16  5.54700196e-01 -1.23168186e-16  8.32050294e-01]
[-7.07106781e-01 -3.14018492e-16  7.07106781e-01 -6.28036983e-16]
[-1.23168186e-16 -8.32050294e-01  1.23168186e-16  5.54700196e-01]
